name: Mi primer workflow
on:
  push: # Evento que dispara el workflow
    branches: [ main ] # branches especifica las ramas que activan el workflow


jobs:
  Mi-primer-job:
    name: Mi primer job
    runs-on: ubuntu-latest
    outputs:
      salida: ${{ steps.imprimir.outputs.respuesta }} # internamente se llama respuesta a la salida del step imprimir
    steps:
    - name: Imprimir
      id: imprimir
      env:
        MI_VARIABLE: Hola mundo
      run: echo "::set-output name=respuesta::${MI_VARIABLE}"

  Mi-segundo-job:
    needs: Mi-primer-job # indica que este job depende del job anterior
    name: Mi segundo job
    runs-on: ubuntu-latest
    steps:
    - name: Imprimir
      id: imprimir
      run: echo ${{needs.Mi-primer-job.outputs.salida}}
